name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-patch:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: install with cpanminus
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: |
            Module::Build
            Devel::PatchPerl
      - name: test patching
        run: |
          perl Build.PL
          ./Build test
  test-macos12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: install with cpanminus
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: |
            Module::Build
            Devel::PatchPerl
            .
      - name: cpanm info
        run: |
          whoami
          ls -al /Users/runner/.cpanm
          sudo chown -R runner /Users/runner/.cpanm
          echo $PATH
          ls /usr/local/Cellar/perl/5.38.2_1/bin
          perl --version
          /usr/local/Cellar/perl/5.38.2_1/bin/cpanm --version
      - name: build perl 5.28.3
        run: |
          export PATH=$PATH:/usr/local/Cellar/perl/5.38.2_1/bin
          echo $PATH
          wget https://www.cpan.org/src/5.0/perl-5.28.3.tar.gz
          tar zxf perl-5.28.3.tar.gz
          cd perl-5.28.3
          export PERL5_PATCHPERL_PLUGIN=Darwin
          patchperl
          ./configure -des
          make
          make test
