name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-patch:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: install with cpanminus
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: |
            Module::Build
      - name: test patching
        run: |
          perl Build.PL
          ./Build test
